# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

pod 'Firebase/Core'
pod 'Firebase/Database'
pod 'Google/SignIn'
pod 'Google'
target 'teste' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  target 'testeTests' do
    inherit! :search_paths
    # Pods for testing
  end

end

target 'teste-tvOS' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for teste-tvOS

  target 'teste-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
